export type ProjectCategory = "privati" | "imprese";

export interface Project {
  slug: string;
  title: string;
  location: string;
  category: ProjectCategory;
  description: string;
  coverImage: string;
  /** All images shown in the masonry detail page */
  images: { src: string; alt: string; tall?: boolean }[];
  /** Used in Featured Projects grid */
  tall?: boolean;
  /** Optional Tailwind object-position class for the cover image */
  coverPosition?: string;
}

export const projects: Project[] = [

  {
    slug: "residenza-av-saluzzo",
    title: "Residenza A+V",
    location: "Saluzzo",
    category: "privati",
    description:
      "Una residenza privata completata con cura dei dettagli, pavimentazioni eleganti e rivestimenti moderni per un'atmosfera accogliente e raffinata.",
    coverImage:
      "/portfolio/privati/Dana del Piaz Privato 3/IMG_2596.webp",
    tall: true,
    coverPosition: "object-[25%_center]",
    images: [
      {
        src: "/portfolio/privati/Dana del Piaz Privato 3/IMG_2596.webp",
        alt: "Residenza A+V Saluzzo - Dettaglio ingresso",
        tall: true,
      },
      {
        src: "/portfolio/privati/Dana del Piaz Privato 3/IMG_2581.webp",
        alt: "Residenza A+V Saluzzo - Vista 2",
        tall: false,
      },
      {
        src: "/portfolio/privati/Dana del Piaz Privato 3/IMG_2582.webp",
        alt: "Residenza A+V Saluzzo - Vista 3",
        tall: false,
      },
      {
        src: "/portfolio/privati/Dana del Piaz Privato 3/IMG_2583.webp",
        alt: "Residenza A+V Saluzzo - Vista 4",
        tall: true,
      },
      {
        src: "/portfolio/privati/Dana del Piaz Privato 3/IMG_2586.webp",
        alt: "Residenza A+V Saluzzo - Vista 5",
        tall: false,
      },
      {
        src: "/portfolio/privati/Dana del Piaz Privato 3/IMG_2587.webp",
        alt: "Residenza A+V Saluzzo - Vista 6",
        tall: false,
      },
      {
        src: "/portfolio/privati/Dana del Piaz Privato 3/IMG_2588.webp",
        alt: "Residenza A+V Saluzzo - Vista 7",
        tall: true,
      },
      {
        src: "/portfolio/privati/Dana del Piaz Privato 3/IMG_2589.webp",
        alt: "Residenza A+V Saluzzo - Vista 8",
        tall: false,
      },
      {
        src: "/portfolio/privati/Dana del Piaz Privato 3/IMG_2591.webp",
        alt: "Residenza A+V Saluzzo - Vista 9",
        tall: false,
      },
      {
        src: "/portfolio/privati/Dana del Piaz Privato 3/IMG_2593.webp",
        alt: "Residenza A+V Saluzzo - Vista 10",
        tall: true,
      },
      {
        src: "/portfolio/privati/Dana del Piaz Privato 3/IMG_2594.webp",
        alt: "Residenza A+V Saluzzo - Vista 11",
        tall: false,
      },
      {
        src: "/portfolio/privati/Dana del Piaz Privato 3/IMG_2595.webp",
        alt: "Residenza A+V Saluzzo - Vista 12",
        tall: false,
      },
      {
        src: "/portfolio/privati/Dana del Piaz Privato 3/IMG_2597.webp",
        alt: "Residenza A+V Saluzzo - Vista 13",
        tall: true,
      },
      {
        src: "/portfolio/privati/Dana del Piaz Privato 3/IMG_2598.webp",
        alt: "Residenza A+V Saluzzo - Vista 14",
        tall: false,
      },
      {
        src: "/portfolio/privati/Dana del Piaz Privato 3/IMG_2599.webp",
        alt: "Residenza A+V Saluzzo - Vista 15",
        tall: true,
      },
    ],
  },
  {
    slug: "casa-a-g-savigliano",
    title: "Casa A+G",
    location: "Savigliano",
    category: "privati",
    description:
      "Una residenza privata dove il design contemporaneo si fonde con materiali di pregio. Pavimenti eleganti e rivestimenti moderni che valorizzano ogni ambiente della casa.",
    coverImage:
      "/portfolio/privati/Casa A+G Savigliano/IMG_06.webp",
    tall: false,
    images: [
      { src: "/portfolio/privati/Casa A+G Savigliano/IMG_01.webp", alt: "Casa A+G Savigliano - Vista 1", tall: true },
      { src: "/portfolio/privati/Casa A+G Savigliano/IMG_02.webp", alt: "Casa A+G Savigliano - Vista 2", tall: false },
      { src: "/portfolio/privati/Casa A+G Savigliano/IMG_03.webp", alt: "Casa A+G Savigliano - Vista 3", tall: false },
      { src: "/portfolio/privati/Casa A+G Savigliano/IMG_04.webp", alt: "Casa A+G Savigliano - Vista 4", tall: true },
      { src: "/portfolio/privati/Casa A+G Savigliano/IMG_05.webp", alt: "Casa A+G Savigliano - Vista 5", tall: false },
      { src: "/portfolio/privati/Casa A+G Savigliano/IMG_06.webp", alt: "Casa A+G Savigliano - Vista 6", tall: false },
      { src: "/portfolio/privati/Casa A+G Savigliano/IMG_07.webp", alt: "Casa A+G Savigliano - Vista 7", tall: true },
      { src: "/portfolio/privati/Casa A+G Savigliano/IMG_08.webp", alt: "Casa A+G Savigliano - Vista 8", tall: false },
      { src: "/portfolio/privati/Casa A+G Savigliano/IMG_09.webp", alt: "Casa A+G Savigliano - Vista 9", tall: false },
      { src: "/portfolio/privati/Casa A+G Savigliano/IMG_10.webp", alt: "Casa A+G Savigliano - Vista 10", tall: true },
      { src: "/portfolio/privati/Casa A+G Savigliano/IMG_11.webp", alt: "Casa A+G Savigliano - Vista 11", tall: false },
      { src: "/portfolio/privati/Casa A+G Savigliano/IMG_12.webp", alt: "Casa A+G Savigliano - Vista 12", tall: true },
    ],
  },
  {
    slug: "rondo-dei-talenti-cuneo",
    title: "Rondo' dei Talenti",
    location: "Cuneo",
    category: "imprese",
    description:
      "Fornitura e posa di pavimenti e rivestimenti per gli spazi del Rondo' dei Talenti a Cuneo. Un progetto commerciale di ampio respiro che coniuga materiali di qualità e soluzioni tecniche studiate per ambienti ad alto traffico.",
    coverImage:
      "/portfolio/imprese/Foto impresa 3 Rondo dei Talenti/2022-07-28 - Rondo dei Talenti-1-IG.webp",
    tall: false,
    images: [
      {
        src: "/portfolio/imprese/Foto impresa 3 Rondo dei Talenti/2022-07-28 - Rondo dei Talenti-1-IG.webp",
        alt: "Rondo' dei Talenti Cuneo - Vista 1",
        tall: false,
      },
      {
        src: "/portfolio/imprese/Foto impresa 3 Rondo dei Talenti/2022-07-28 - Rondo dei Talenti-14.webp",
        alt: "Rondo' dei Talenti Cuneo - Vista 2",
        tall: true,
      },
      {
        src: "/portfolio/imprese/Foto impresa 3 Rondo dei Talenti/2022-07-28 - Rondo dei Talenti-2-IG-2.webp",
        alt: "Rondo' dei Talenti Cuneo - Vista 3",
        tall: false,
      },
      {
        src: "/portfolio/imprese/Foto impresa 3 Rondo dei Talenti/2022-07-28 - Rondo dei Talenti-3-IG.webp",
        alt: "Rondo' dei Talenti Cuneo - Vista 4",
        tall: false,
      },
      {
        src: "/portfolio/imprese/Foto impresa 3 Rondo dei Talenti/2022-07-28 - Rondo dei Talenti-5-IG.webp",
        alt: "Rondo' dei Talenti Cuneo - Vista 5",
        tall: true,
      },
      {
        src: "/portfolio/imprese/Foto impresa 3 Rondo dei Talenti/2022-07-28 - Rondo dei Talenti-6-IG.webp",
        alt: "Rondo' dei Talenti Cuneo - Vista 6",
        tall: false,
      },
      {
        src: "/portfolio/imprese/Foto impresa 3 Rondo dei Talenti/2022-07-28 - Rondo dei Talenti-6.webp",
        alt: "Rondo' dei Talenti Cuneo - Vista 7",
        tall: true,
      },
      {
        src: "/portfolio/imprese/Foto impresa 3 Rondo dei Talenti/2022-10-04 - Rondo dei Talenti-10.webp",
        alt: "Rondo' dei Talenti Cuneo - Vista 8",
        tall: false,
      },
      {
        src: "/portfolio/imprese/Foto impresa 3 Rondo dei Talenti/2022-10-04 - Rondo dei Talenti-14.webp",
        alt: "Rondo' dei Talenti Cuneo - Vista 9",
        tall: true,
      },
      {
        src: "/portfolio/imprese/Foto impresa 3 Rondo dei Talenti/2022-10-04 - Rondo dei Talenti-5.webp",
        alt: "Rondo' dei Talenti Cuneo - Vista 10",
        tall: false,
      },
      {
        src: "/portfolio/imprese/Foto impresa 3 Rondo dei Talenti/2022-10-04 - Rondo dei Talenti-6.webp",
        alt: "Rondo' dei Talenti Cuneo - Vista 11",
        tall: false,
      },
      {
        src: "/portfolio/imprese/Foto impresa 3 Rondo dei Talenti/2022-10-04 - Rondo dei Talenti-7.webp",
        alt: "Rondo' dei Talenti Cuneo - Vista 12",
        tall: true,
      },
      {
        src: "/portfolio/imprese/Foto impresa 3 Rondo dei Talenti/510-Modifica.webp",
        alt: "Rondo' dei Talenti Cuneo - Vista 13",
        tall: false,
      },
    ],
  },

  {
    slug: "villa-m-c",
    title: "Villa M+C",
    location: "Piemonte",
    category: "privati",
    description: "Progetto residenziale in cui l'attenzione per il dettaglio si unisce alla scelta di materiali pregiati, definendo spazi dal carattere moderno ed elegante.",
    coverImage: "/portfolio/privati/Villa M+C/media__1782398929883.webp",
    tall: true,
    images: [
      { src: "/portfolio/privati/Villa M+C/nuova_foto_1.webp", alt: "Villa M+C - Vista 1", tall: false },
      { src: "/portfolio/privati/Villa M+C/nuova_foto_2.webp", alt: "Villa M+C - Vista 2", tall: true },
      { src: "/portfolio/privati/Villa M+C/nuova_foto_3.webp", alt: "Villa M+C - Vista 3", tall: false },
      { src: "/portfolio/privati/Villa M+C/nuova_foto_4.webp", alt: "Villa M+C - Vista 4", tall: false },
      { src: "/portfolio/privati/Villa M+C/nuova_foto_5.webp", alt: "Villa M+C - Vista 5", tall: true },
      { src: "/portfolio/privati/Villa M+C/media__1782398772505.webp", alt: "Villa M+C - Vista 6", tall: false },
      { src: "/portfolio/privati/Villa M+C/media__1782398772571.webp", alt: "Villa M+C - Vista 7", tall: false },
      { src: "/portfolio/privati/Villa M+C/media__1782398772635.webp", alt: "Villa M+C - Vista 8", tall: true },
      { src: "/portfolio/privati/Villa M+C/media__1782398772653.webp", alt: "Villa M+C - Vista 9", tall: false },
      { src: "/portfolio/privati/Villa M+C/media__1782398772719.webp", alt: "Villa M+C - Vista 10", tall: false },
      { src: "/portfolio/privati/Villa M+C/media__1782398869850.webp", alt: "Villa M+C - Vista 11", tall: true },
      { src: "/portfolio/privati/Villa M+C/media__1782398869871.webp", alt: "Villa M+C - Vista 12", tall: false },
      { src: "/portfolio/privati/Villa M+C/media__1782398869915.webp", alt: "Villa M+C - Vista 13", tall: false },
      { src: "/portfolio/privati/Villa M+C/media__1782398869943.webp", alt: "Villa M+C - Vista 14", tall: true },
      { src: "/portfolio/privati/Villa M+C/media__1782398869955.webp", alt: "Villa M+C - Vista 15", tall: false },
      { src: "/portfolio/privati/Villa M+C/media__1782398929727.webp", alt: "Villa M+C - Vista 16", tall: false },
      { src: "/portfolio/privati/Villa M+C/media__1782398929798.webp", alt: "Villa M+C - Vista 17", tall: true },
      { src: "/portfolio/privati/Villa M+C/media__1782398929829.webp", alt: "Villa M+C - Vista 18", tall: false },
      { src: "/portfolio/privati/Villa M+C/media__1782398929883.webp", alt: "Villa M+C - Vista 19", tall: false },
      { src: "/portfolio/privati/Villa M+C/media__1782398929898.webp", alt: "Villa M+C - Vista 20", tall: true },
      { src: "/portfolio/privati/Villa M+C/media__1782398970865.webp", alt: "Villa M+C - Vista 21", tall: false },
    ],
  },

  // â”€â”€ 5 â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  {
    slug: "villa-ad-cavallermaggiore",
    title: "Villa A+D",
    location: "Cavallermaggiore",
    category: "privati",
    description: "Villa privata completata con pavimenti e rivestimenti di pregio in ogni ambiente. Un progetto residenziale che coniuga eleganza e funzionalitÃ .",
    coverImage: "/portfolio/privati/Danilo Allasia Privato 4/IMG_4983.webp",
    tall: false,
    images: [
      { src: "/portfolio/privati/Danilo Allasia Privato 4/IMG_4983.webp", alt: "Villa A+D Cavallermaggiore - Vista 1", tall: false },
      { src: "/portfolio/privati/Danilo Allasia Privato 4/IMG_4984.webp", alt: "Villa A+D Cavallermaggiore - Vista 2", tall: true },
      { src: "/portfolio/privati/Danilo Allasia Privato 4/IMG_4985.webp", alt: "Villa A+D Cavallermaggiore - Vista 3", tall: false },
      { src: "/portfolio/privati/Danilo Allasia Privato 4/IMG_4986.webp", alt: "Villa A+D Cavallermaggiore - Vista 4", tall: false },
      { src: "/portfolio/privati/Danilo Allasia Privato 4/IMG_4987.webp", alt: "Villa A+D Cavallermaggiore - Vista 5", tall: true },
      { src: "/portfolio/privati/Danilo Allasia Privato 4/IMG_4988.webp", alt: "Villa A+D Cavallermaggiore - Vista 6", tall: false },
      { src: "/portfolio/privati/Danilo Allasia Privato 4/IMG_4989.webp", alt: "Villa A+D Cavallermaggiore - Vista 7", tall: false },
      { src: "/portfolio/privati/Danilo Allasia Privato 4/IMG_4991.webp", alt: "Villa A+D Cavallermaggiore - Vista 8", tall: true },
      { src: "/portfolio/privati/Danilo Allasia Privato 4/IMG_4993.webp", alt: "Villa A+D Cavallermaggiore - Vista 9", tall: false },
      { src: "/portfolio/privati/Danilo Allasia Privato 4/IMG_4994.webp", alt: "Villa A+D Cavallermaggiore - Vista 10", tall: false },
      { src: "/portfolio/privati/Danilo Allasia Privato 4/IMG_4995.webp", alt: "Villa A+D Cavallermaggiore - Vista 11", tall: true },
      { src: "/portfolio/privati/Danilo Allasia Privato 4/IMG_4997.webp", alt: "Villa A+D Cavallermaggiore - Vista 12", tall: false },
      { src: "/portfolio/privati/Danilo Allasia Privato 4/IMG_4997_01.webp", alt: "Villa A+D Cavallermaggiore - Vista 13", tall: false },
      { src: "/portfolio/privati/Danilo Allasia Privato 4/IMG_4997_02.webp", alt: "Villa A+D Cavallermaggiore - Vista 14", tall: true },
      { src: "/portfolio/privati/Danilo Allasia Privato 4/IMG_5001.webp", alt: "Villa A+D Cavallermaggiore - Vista 15", tall: false },
      { src: "/portfolio/privati/Danilo Allasia Privato 4/IMG_5003.webp", alt: "Villa A+D Cavallermaggiore - Vista 16", tall: false },
      { src: "/portfolio/privati/Danilo Allasia Privato 4/IMG_5005.webp", alt: "Villa A+D Cavallermaggiore - Vista 17", tall: true },
      { src: "/portfolio/privati/Danilo Allasia Privato 4/IMG_5007.webp", alt: "Villa A+D Cavallermaggiore - Vista 18", tall: false },
      { src: "/portfolio/privati/Danilo Allasia Privato 4/IMG_5007_01.webp", alt: "Villa A+D Cavallermaggiore - Vista 19", tall: false },
      { src: "/portfolio/privati/Danilo Allasia Privato 4/IMG_5007_02.webp", alt: "Villa A+D Cavallermaggiore - Vista 20", tall: true },
      { src: "/portfolio/privati/Danilo Allasia Privato 4/IMG_5008.webp", alt: "Villa A+D Cavallermaggiore - Vista 21", tall: false },
      { src: "/portfolio/privati/Danilo Allasia Privato 4/IMG_5011.webp", alt: "Villa A+D Cavallermaggiore - Vista 22", tall: false },
      { src: "/portfolio/privati/Danilo Allasia Privato 4/IMG_5011_01.webp", alt: "Villa A+D Cavallermaggiore - Vista 23", tall: true },
      { src: "/portfolio/privati/Danilo Allasia Privato 4/IMG_5011_02.webp", alt: "Villa A+D Cavallermaggiore - Vista 24", tall: false },
      { src: "/portfolio/privati/Danilo Allasia Privato 4/IMG_5013.webp", alt: "Villa A+D Cavallermaggiore - Vista 25", tall: false },
      { src: "/portfolio/privati/Danilo Allasia Privato 4/IMG_5014.webp", alt: "Villa A+D Cavallermaggiore - Vista 26", tall: true },
      { src: "/portfolio/privati/Danilo Allasia Privato 4/IMG_5017.webp", alt: "Villa A+D Cavallermaggiore - Vista 27", tall: false },
      { src: "/portfolio/privati/Danilo Allasia Privato 4/IMG_5018.webp", alt: "Villa A+D Cavallermaggiore - Vista 28", tall: false },
      { src: "/portfolio/privati/Danilo Allasia Privato 4/IMG_5021.webp", alt: "Villa A+D Cavallermaggiore - Vista 29", tall: true },
      { src: "/portfolio/privati/Danilo Allasia Privato 4/IMG_5023.webp", alt: "Villa A+D Cavallermaggiore - Vista 30", tall: false },
      { src: "/portfolio/privati/Danilo Allasia Privato 4/IMG_5024.webp", alt: "Villa A+D Cavallermaggiore - Vista 31", tall: false },
      { src: "/portfolio/privati/Danilo Allasia Privato 4/IMG_5025.webp", alt: "Villa A+D Cavallermaggiore - Vista 32", tall: true },
      { src: "/portfolio/privati/Danilo Allasia Privato 4/IMG_5028.webp", alt: "Villa A+D Cavallermaggiore - Vista 33", tall: false },
      { src: "/portfolio/privati/Danilo Allasia Privato 4/IMG_5029.webp", alt: "Villa A+D Cavallermaggiore - Vista 34", tall: false },
      { src: "/portfolio/privati/Danilo Allasia Privato 4/IMG_5030.webp", alt: "Villa A+D Cavallermaggiore - Vista 35", tall: true },
      { src: "/portfolio/privati/Danilo Allasia Privato 4/IMG_5032.webp", alt: "Villa A+D Cavallermaggiore - Vista 36", tall: false },
      { src: "/portfolio/privati/Danilo Allasia Privato 4/IMG_5033.webp", alt: "Villa A+D Cavallermaggiore - Vista 37", tall: false },
      { src: "/portfolio/privati/Danilo Allasia Privato 4/IMG_5034.webp", alt: "Villa A+D Cavallermaggiore - Vista 38", tall: true },
      { src: "/portfolio/privati/Danilo Allasia Privato 4/IMG_5035.webp", alt: "Villa A+D Cavallermaggiore - Vista 39", tall: false },
      { src: "/portfolio/privati/Danilo Allasia Privato 4/IMG_5036.webp", alt: "Villa A+D Cavallermaggiore - Vista 40", tall: false },
      { src: "/portfolio/privati/Danilo Allasia Privato 4/IMG_5037.webp", alt: "Villa A+D Cavallermaggiore - Vista 41", tall: true },
      { src: "/portfolio/privati/Danilo Allasia Privato 4/IMG_5038.webp", alt: "Villa A+D Cavallermaggiore - Vista 42", tall: false },
      { src: "/portfolio/privati/Danilo Allasia Privato 4/IMG_5039.webp", alt: "Villa A+D Cavallermaggiore - Vista 43", tall: false },
      { src: "/portfolio/privati/Danilo Allasia Privato 4/IMG_5040.webp", alt: "Villa A+D Cavallermaggiore - Vista 44", tall: true },
      { src: "/portfolio/privati/Danilo Allasia Privato 4/IMG_5042.webp", alt: "Villa A+D Cavallermaggiore - Vista 45", tall: false },
      { src: "/portfolio/privati/Danilo Allasia Privato 4/IMG_5043.webp", alt: "Villa A+D Cavallermaggiore - Vista 46", tall: false },
      { src: "/portfolio/privati/Danilo Allasia Privato 4/IMG_5044.webp", alt: "Villa A+D Cavallermaggiore - Vista 47", tall: true },
      { src: "/portfolio/privati/Danilo Allasia Privato 4/IMG_5046.webp", alt: "Villa A+D Cavallermaggiore - Vista 48", tall: false },
      { src: "/portfolio/privati/Danilo Allasia Privato 4/IMG_5047.webp", alt: "Villa A+D Cavallermaggiore - Vista 49", tall: false },
      { src: "/portfolio/privati/Danilo Allasia Privato 4/IMG_5048.webp", alt: "Villa A+D Cavallermaggiore - Vista 50", tall: true },
      { src: "/portfolio/privati/Danilo Allasia Privato 4/IMG_5051.webp", alt: "Villa A+D Cavallermaggiore - Vista 51", tall: false },
      { src: "/portfolio/privati/Danilo Allasia Privato 4/IMG_5052.webp", alt: "Villa A+D Cavallermaggiore - Vista 52", tall: false },
      { src: "/portfolio/privati/Danilo Allasia Privato 4/IMG_5054.webp", alt: "Villa A+D Cavallermaggiore - Vista 53", tall: true },
      { src: "/portfolio/privati/Danilo Allasia Privato 4/IMG_5058.webp", alt: "Villa A+D Cavallermaggiore - Vista 54", tall: false },
      { src: "/portfolio/privati/Danilo Allasia Privato 4/IMG_5058_01.webp", alt: "Villa A+D Cavallermaggiore - Vista 55", tall: false },
      { src: "/portfolio/privati/Danilo Allasia Privato 4/IMG_5058_02.webp", alt: "Villa A+D Cavallermaggiore - Vista 56", tall: true },
      { src: "/portfolio/privati/Danilo Allasia Privato 4/IMG_5059.webp", alt: "Villa A+D Cavallermaggiore - Vista 57", tall: false },
      { src: "/portfolio/privati/Danilo Allasia Privato 4/IMG_5064.webp", alt: "Villa A+D Cavallermaggiore - Vista 58", tall: false },
      { src: "/portfolio/privati/Danilo Allasia Privato 4/IMG_5064_01.webp", alt: "Villa A+D Cavallermaggiore - Vista 59", tall: true },
      { src: "/portfolio/privati/Danilo Allasia Privato 4/IMG_5064_02.webp", alt: "Villa A+D Cavallermaggiore - Vista 60", tall: false },
      { src: "/portfolio/privati/Danilo Allasia Privato 4/IMG_5068.webp", alt: "Villa A+D Cavallermaggiore - Vista 61", tall: false },
      { src: "/portfolio/privati/Danilo Allasia Privato 4/IMG_5070.webp", alt: "Villa A+D Cavallermaggiore - Vista 62", tall: true },
      { src: "/portfolio/privati/Danilo Allasia Privato 4/IMG_5071.webp", alt: "Villa A+D Cavallermaggiore - Vista 63", tall: false },
      { src: "/portfolio/privati/Danilo Allasia Privato 4/IMG_5072.webp", alt: "Villa A+D Cavallermaggiore - Vista 64", tall: false },
      { src: "/portfolio/privati/Danilo Allasia Privato 4/IMG_5074.webp", alt: "Villa A+D Cavallermaggiore - Vista 65", tall: true },
      { src: "/portfolio/privati/Danilo Allasia Privato 4/IMG_5076.webp", alt: "Villa A+D Cavallermaggiore - Vista 66", tall: false },
      { src: "/portfolio/privati/Danilo Allasia Privato 4/IMG_5077.webp", alt: "Villa A+D Cavallermaggiore - Vista 67", tall: false },
      { src: "/portfolio/privati/Danilo Allasia Privato 4/IMG_5080.webp", alt: "Villa A+D Cavallermaggiore - Vista 68", tall: true },
      { src: "/portfolio/privati/Danilo Allasia Privato 4/IMG_5081.webp", alt: "Villa A+D Cavallermaggiore - Vista 69", tall: false },
      { src: "/portfolio/privati/Danilo Allasia Privato 4/IMG_5085.webp", alt: "Villa A+D Cavallermaggiore - Vista 70", tall: false },
      { src: "/portfolio/privati/Danilo Allasia Privato 4/IMG_5086.webp", alt: "Villa A+D Cavallermaggiore - Vista 71", tall: true },
      { src: "/portfolio/privati/Danilo Allasia Privato 4/IMG_5089.webp", alt: "Villa A+D Cavallermaggiore - Vista 72", tall: false },
      { src: "/portfolio/privati/Danilo Allasia Privato 4/IMG_5090.webp", alt: "Villa A+D Cavallermaggiore - Vista 73", tall: false },
      { src: "/portfolio/privati/Danilo Allasia Privato 4/IMG_5092.webp", alt: "Villa A+D Cavallermaggiore - Vista 74", tall: true },
      { src: "/portfolio/privati/Danilo Allasia Privato 4/IMG_5093.webp", alt: "Villa A+D Cavallermaggiore - Vista 75", tall: false },
      { src: "/portfolio/privati/Danilo Allasia Privato 4/IMG_5094.webp", alt: "Villa A+D Cavallermaggiore - Vista 76", tall: false },
      { src: "/portfolio/privati/Danilo Allasia Privato 4/IMG_5099.webp", alt: "Villa A+D Cavallermaggiore - Vista 77", tall: true },
      { src: "/portfolio/privati/Danilo Allasia Privato 4/IMG_5100.webp", alt: "Villa A+D Cavallermaggiore - Vista 78", tall: false },
      { src: "/portfolio/privati/Danilo Allasia Privato 4/IMG_5102.webp", alt: "Villa A+D Cavallermaggiore - Vista 79", tall: false },
      { src: "/portfolio/privati/Danilo Allasia Privato 4/IMG_5104.webp", alt: "Villa A+D Cavallermaggiore - Vista 80", tall: true },
      { src: "/portfolio/privati/Danilo Allasia Privato 4/IMG_5107.webp", alt: "Villa A+D Cavallermaggiore - Vista 81", tall: false },
      { src: "/portfolio/privati/Danilo Allasia Privato 4/IMG_5108.webp", alt: "Villa A+D Cavallermaggiore - Vista 82", tall: false },
      { src: "/portfolio/privati/Danilo Allasia Privato 4/IMG_5108_01.webp", alt: "Villa A+D Cavallermaggiore - Vista 83", tall: true },
      { src: "/portfolio/privati/Danilo Allasia Privato 4/IMG_5108_02.webp", alt: "Villa A+D Cavallermaggiore - Vista 84", tall: false },
      { src: "/portfolio/privati/Danilo Allasia Privato 4/IMG_5112.webp", alt: "Villa A+D Cavallermaggiore - Vista 85", tall: false },
      { src: "/portfolio/privati/Danilo Allasia Privato 4/IMG_5113.webp", alt: "Villa A+D Cavallermaggiore - Vista 86", tall: true },
      { src: "/portfolio/privati/Danilo Allasia Privato 4/IMG_5117.webp", alt: "Villa A+D Cavallermaggiore - Vista 87", tall: false },
    ],
  },

  // â”€â”€ 6 â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  {
    slug: "residenza-ev-savigliano",
    title: "Residenza E+V",
    location: "Savigliano",
    category: "privati",
    description: "Residenza privata con pavimenti e rivestimenti su misura. Un progetto che unisce materiali selezionati e cura del dettaglio per un risultato raffinato e duraturo.",
    coverImage: "/portfolio/privati/Vaglienti Elisa Privato 5/IMG_5106.webp",
    tall: true,
    images: [
      { src: "/portfolio/privati/Vaglienti Elisa Privato 5/IMG_5106.webp", alt: "Residenza E+V Savigliano - Vista 1", tall: false },
      { src: "/portfolio/privati/Vaglienti Elisa Privato 5/IMG_5107.webp", alt: "Residenza E+V Savigliano - Vista 2", tall: true },
      { src: "/portfolio/privati/Vaglienti Elisa Privato 5/IMG_5108.webp", alt: "Residenza E+V Savigliano - Vista 3", tall: false },
      { src: "/portfolio/privati/Vaglienti Elisa Privato 5/IMG_5109.webp", alt: "Residenza E+V Savigliano - Vista 4", tall: false },
      { src: "/portfolio/privati/Vaglienti Elisa Privato 5/IMG_5111.webp", alt: "Residenza E+V Savigliano - Vista 5", tall: true },
      { src: "/portfolio/privati/Vaglienti Elisa Privato 5/IMG_5112.webp", alt: "Residenza E+V Savigliano - Vista 6", tall: false },
      { src: "/portfolio/privati/Vaglienti Elisa Privato 5/IMG_5113.webp", alt: "Residenza E+V Savigliano - Vista 7", tall: false },
      { src: "/portfolio/privati/Vaglienti Elisa Privato 5/IMG_5117.webp", alt: "Residenza E+V Savigliano - Vista 8", tall: true },
      { src: "/portfolio/privati/Vaglienti Elisa Privato 5/IMG_5119.webp", alt: "Residenza E+V Savigliano - Vista 9", tall: false },
      { src: "/portfolio/privati/Vaglienti Elisa Privato 5/IMG_5120.webp", alt: "Residenza E+V Savigliano - Vista 10", tall: false },
      { src: "/portfolio/privati/Vaglienti Elisa Privato 5/IMG_5120_01.webp", alt: "Residenza E+V Savigliano - Vista 11", tall: true },
      { src: "/portfolio/privati/Vaglienti Elisa Privato 5/IMG_5120_02.webp", alt: "Residenza E+V Savigliano - Vista 12", tall: false },
      { src: "/portfolio/privati/Vaglienti Elisa Privato 5/IMG_5122.webp", alt: "Residenza E+V Savigliano - Vista 13", tall: false },
      { src: "/portfolio/privati/Vaglienti Elisa Privato 5/IMG_5124.webp", alt: "Residenza E+V Savigliano - Vista 14", tall: true },
      { src: "/portfolio/privati/Vaglienti Elisa Privato 5/IMG_5126.webp", alt: "Residenza E+V Savigliano - Vista 15", tall: false },
      { src: "/portfolio/privati/Vaglienti Elisa Privato 5/IMG_5128.webp", alt: "Residenza E+V Savigliano - Vista 16", tall: false },
      { src: "/portfolio/privati/Vaglienti Elisa Privato 5/IMG_5129.webp", alt: "Residenza E+V Savigliano - Vista 17", tall: true },
      { src: "/portfolio/privati/Vaglienti Elisa Privato 5/IMG_5134.webp", alt: "Residenza E+V Savigliano - Vista 18", tall: false },
      { src: "/portfolio/privati/Vaglienti Elisa Privato 5/IMG_5135.webp", alt: "Residenza E+V Savigliano - Vista 19", tall: false },
      { src: "/portfolio/privati/Vaglienti Elisa Privato 5/IMG_5136.webp", alt: "Residenza E+V Savigliano - Vista 20", tall: true },
      { src: "/portfolio/privati/Vaglienti Elisa Privato 5/IMG_5139.webp", alt: "Residenza E+V Savigliano - Vista 21", tall: false },
      { src: "/portfolio/privati/Vaglienti Elisa Privato 5/IMG_5140.webp", alt: "Residenza E+V Savigliano - Vista 22", tall: false },
      { src: "/portfolio/privati/Vaglienti Elisa Privato 5/IMG_5141.webp", alt: "Residenza E+V Savigliano - Vista 23", tall: true },
      { src: "/portfolio/privati/Vaglienti Elisa Privato 5/IMG_5144.webp", alt: "Residenza E+V Savigliano - Vista 24", tall: false },
      { src: "/portfolio/privati/Vaglienti Elisa Privato 5/IMG_5147.webp", alt: "Residenza E+V Savigliano - Vista 25", tall: false },
      { src: "/portfolio/privati/Vaglienti Elisa Privato 5/IMG_5151.webp", alt: "Residenza E+V Savigliano - Vista 26", tall: true },
      { src: "/portfolio/privati/Vaglienti Elisa Privato 5/IMG_5152.webp", alt: "Residenza E+V Savigliano - Vista 27", tall: false },
      { src: "/portfolio/privati/Vaglienti Elisa Privato 5/IMG_5153.webp", alt: "Residenza E+V Savigliano - Vista 28", tall: false },
      { src: "/portfolio/privati/Vaglienti Elisa Privato 5/IMG_5153_01.webp", alt: "Residenza E+V Savigliano - Vista 29", tall: true },
      { src: "/portfolio/privati/Vaglienti Elisa Privato 5/IMG_5153_02.webp", alt: "Residenza E+V Savigliano - Vista 30", tall: false },
      { src: "/portfolio/privati/Vaglienti Elisa Privato 5/IMG_5154.webp", alt: "Residenza E+V Savigliano - Vista 31", tall: false },
      { src: "/portfolio/privati/Vaglienti Elisa Privato 5/IMG_5156.webp", alt: "Residenza E+V Savigliano - Vista 32", tall: true },
      { src: "/portfolio/privati/Vaglienti Elisa Privato 5/IMG_5157.webp", alt: "Residenza E+V Savigliano - Vista 33", tall: false },
      { src: "/portfolio/privati/Vaglienti Elisa Privato 5/IMG_5159.webp", alt: "Residenza E+V Savigliano - Vista 34", tall: false },
      { src: "/portfolio/privati/Vaglienti Elisa Privato 5/IMG_5161.webp", alt: "Residenza E+V Savigliano - Vista 35", tall: true },
      { src: "/portfolio/privati/Vaglienti Elisa Privato 5/IMG_5162.webp", alt: "Residenza E+V Savigliano - Vista 36", tall: false },
      { src: "/portfolio/privati/Vaglienti Elisa Privato 5/IMG_5163.webp", alt: "Residenza E+V Savigliano - Vista 37", tall: false },
      { src: "/portfolio/privati/Vaglienti Elisa Privato 5/IMG_5165.webp", alt: "Residenza E+V Savigliano - Vista 38", tall: true },
      { src: "/portfolio/privati/Vaglienti Elisa Privato 5/IMG_5167.webp", alt: "Residenza E+V Savigliano - Vista 39", tall: false },
      { src: "/portfolio/privati/Vaglienti Elisa Privato 5/IMG_5174.webp", alt: "Residenza E+V Savigliano - Vista 40", tall: false },
      { src: "/portfolio/privati/Vaglienti Elisa Privato 5/IMG_5176.webp", alt: "Residenza E+V Savigliano - Vista 41", tall: true },
      { src: "/portfolio/privati/Vaglienti Elisa Privato 5/IMG_5181.webp", alt: "Residenza E+V Savigliano - Vista 42", tall: false },
    ],
  },

  // â”€â”€ 7 â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  {
    slug: "villa-m-m-cuneo",
    title: "Villa M+M",
    location: "Cuneo",
    category: "privati",
    description: "Villa privata con pavimentazioni e rivestimenti di qualità selezionati per valorizzare ogni ambiente, dal soggiorno ai bagni.",
    coverImage: "/portfolio/privati/Villa Privato 6/DSC_7810.webp",
    tall: false,
    images: [
      { src: "/portfolio/privati/Villa Privato 6/DSC_7810.webp", alt: "Villa M+M Cuneo - Vista 1", tall: false },
      { src: "/portfolio/privati/Villa Privato 6/DSC_7811.webp", alt: "Villa M+M Cuneo - Vista 2", tall: true },
      { src: "/portfolio/privati/Villa Privato 6/DSC_7813.webp", alt: "Villa M+M Cuneo - Vista 3", tall: false },
      { src: "/portfolio/privati/Villa Privato 6/DSC_7814.webp", alt: "Villa M+M Cuneo - Vista 4", tall: false },
      { src: "/portfolio/privati/Villa Privato 6/DSC_7815.webp", alt: "Villa M+M Cuneo - Vista 5", tall: true },
      { src: "/portfolio/privati/Villa Privato 6/DSC_7816.webp", alt: "Villa M+M Cuneo - Vista 6", tall: false },
      { src: "/portfolio/privati/Villa Privato 6/DSC_7817.webp", alt: "Villa M+M Cuneo - Vista 7", tall: false },
      { src: "/portfolio/privati/Villa Privato 6/DSC_7818.webp", alt: "Villa M+M Cuneo - Vista 8", tall: true },
      { src: "/portfolio/privati/Villa Privato 6/DSC_7819.webp", alt: "Villa M+M Cuneo - Vista 9", tall: false },
      { src: "/portfolio/privati/Villa Privato 6/DSC_7820.webp", alt: "Villa M+M Cuneo - Vista 10", tall: false },
      { src: "/portfolio/privati/Villa Privato 6/DSC_7821.webp", alt: "Villa M+M Cuneo - Vista 11", tall: true },
      { src: "/portfolio/privati/Villa Privato 6/DSC_7822.webp", alt: "Villa M+M Cuneo - Vista 12", tall: false },
      { src: "/portfolio/privati/Villa Privato 6/DSC_7823.webp", alt: "Villa M+M Cuneo - Vista 13", tall: false },
      { src: "/portfolio/privati/Villa Privato 6/DSC_7824.webp", alt: "Villa M+M Cuneo - Vista 14", tall: true },
      { src: "/portfolio/privati/Villa Privato 6/DSC_7825.webp", alt: "Villa M+M Cuneo - Vista 15", tall: false },
      { src: "/portfolio/privati/Villa Privato 6/DSC_7826.webp", alt: "Villa M+M Cuneo - Vista 16", tall: false },
      { src: "/portfolio/privati/Villa Privato 6/DSC_7827.webp", alt: "Villa M+M Cuneo - Vista 17", tall: true },
      { src: "/portfolio/privati/Villa Privato 6/DSC_7828.webp", alt: "Villa M+M Cuneo - Vista 18", tall: false },
      { src: "/portfolio/privati/Villa Privato 6/DSC_7829.webp", alt: "Villa M+M Cuneo - Vista 19", tall: false },
      { src: "/portfolio/privati/Villa Privato 6/DSC_7830.webp", alt: "Villa M+M Cuneo - Vista 20", tall: true },
      { src: "/portfolio/privati/Villa Privato 6/DSC_7831.webp", alt: "Villa M+M Cuneo - Vista 21", tall: false },
      { src: "/portfolio/privati/Villa Privato 6/DSC_7832.webp", alt: "Villa M+M Cuneo - Vista 22", tall: false },
      { src: "/portfolio/privati/Villa Privato 6/DSC_7833.webp", alt: "Villa M+M Cuneo - Vista 23", tall: true },
      { src: "/portfolio/privati/Villa Privato 6/DSC_7834.webp", alt: "Villa M+M Cuneo - Vista 24", tall: false },
      { src: "/portfolio/privati/Villa Privato 6/DSC_7835.webp", alt: "Villa M+M Cuneo - Vista 25", tall: false },
      { src: "/portfolio/privati/Villa Privato 6/DSC_7836.webp", alt: "Villa M+M Cuneo - Vista 26", tall: true },
      { src: "/portfolio/privati/Villa Privato 6/DSC_7837.webp", alt: "Villa M+M Cuneo - Vista 27", tall: false },
      { src: "/portfolio/privati/Villa Privato 6/DSC_7838.webp", alt: "Villa M+M Cuneo - Vista 28", tall: false },
      { src: "/portfolio/privati/Villa Privato 6/DSC_7839.webp", alt: "Villa M+M Cuneo - Vista 29", tall: true },
      { src: "/portfolio/privati/Villa Privato 6/DSC_7840.webp", alt: "Villa M+M Cuneo - Vista 30", tall: false },
      { src: "/portfolio/privati/Villa Privato 6/DSC_7841.webp", alt: "Villa M+M Cuneo - Vista 31", tall: false },
      { src: "/portfolio/privati/Villa Privato 6/DSC_7842.webp", alt: "Villa M+M Cuneo - Vista 32", tall: true },
      { src: "/portfolio/privati/Villa Privato 6/DSC_7843.webp", alt: "Villa M+M Cuneo - Vista 33", tall: false },
      { src: "/portfolio/privati/Villa Privato 6/DSC_7844.webp", alt: "Villa M+M Cuneo - Vista 34", tall: false },
      { src: "/portfolio/privati/Villa Privato 6/DSC_7845.webp", alt: "Villa M+M Cuneo - Vista 35", tall: true },
      { src: "/portfolio/privati/Villa Privato 6/DSC_7846.webp", alt: "Villa M+M Cuneo - Vista 36", tall: false },
      { src: "/portfolio/privati/Villa Privato 6/DSC_7847.webp", alt: "Villa M+M Cuneo - Vista 37", tall: false },
      { src: "/portfolio/privati/Villa Privato 6/DSC_7848.webp", alt: "Villa M+M Cuneo - Vista 38", tall: true },
      { src: "/portfolio/privati/Villa Privato 6/DSC_7849.webp", alt: "Villa M+M Cuneo - Vista 39", tall: false },
      { src: "/portfolio/privati/Villa Privato 6/DSC_7850.webp", alt: "Villa M+M Cuneo - Vista 40", tall: false },
      { src: "/portfolio/privati/Villa Privato 6/DSC_7851.webp", alt: "Villa M+M Cuneo - Vista 41", tall: true },
    ],
  },

  // â”€â”€ 8 â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  {
    slug: "casa-e-r-torino",
    title: "Casa E+R",
    location: "Torino",
    category: "privati",
    description: "Villa privata con pavimentazioni e rivestimenti di qualità selezionati per valorizzare ogni ambiente.",
    coverImage: "/portfolio/privati/Villa Privato 7/DSC_7908.webp",
    tall: true,
    images: [
      { src: "/portfolio/privati/Villa Privato 7/DSC_7908.webp", alt: "Casa E+R Torino - Vista 1", tall: false },
      { src: "/portfolio/privati/Villa Privato 7/DSC_7909.webp", alt: "Casa E+R Torino - Vista 2", tall: true },
      { src: "/portfolio/privati/Villa Privato 7/DSC_7910.webp", alt: "Casa E+R Torino - Vista 3", tall: false },
      { src: "/portfolio/privati/Villa Privato 7/DSC_7911.webp", alt: "Casa E+R Torino - Vista 4", tall: false },
      { src: "/portfolio/privati/Villa Privato 7/DSC_7912.webp", alt: "Casa E+R Torino - Vista 5", tall: true },
      { src: "/portfolio/privati/Villa Privato 7/DSC_7913.webp", alt: "Casa E+R Torino - Vista 6", tall: false },
      { src: "/portfolio/privati/Villa Privato 7/DSC_7914.webp", alt: "Casa E+R Torino - Vista 7", tall: false },
      { src: "/portfolio/privati/Villa Privato 7/DSC_7915.webp", alt: "Casa E+R Torino - Vista 8", tall: true },
      { src: "/portfolio/privati/Villa Privato 7/DSC_7916.webp", alt: "Casa E+R Torino - Vista 9", tall: false },
      { src: "/portfolio/privati/Villa Privato 7/DSC_7917.webp", alt: "Casa E+R Torino - Vista 10", tall: false },
      { src: "/portfolio/privati/Villa Privato 7/DSC_7918.webp", alt: "Casa E+R Torino - Vista 11", tall: true },
      { src: "/portfolio/privati/Villa Privato 7/DSC_7919.webp", alt: "Casa E+R Torino - Vista 12", tall: false },
      { src: "/portfolio/privati/Villa Privato 7/DSC_7920.webp", alt: "Casa E+R Torino - Vista 13", tall: false },
      { src: "/portfolio/privati/Villa Privato 7/DSC_7921.webp", alt: "Casa E+R Torino - Vista 14", tall: true },
      { src: "/portfolio/privati/Villa Privato 7/DSC_7922.webp", alt: "Casa E+R Torino - Vista 15", tall: false },
      { src: "/portfolio/privati/Villa Privato 7/DSC_7923.webp", alt: "Casa E+R Torino - Vista 16", tall: false },
      { src: "/portfolio/privati/Villa Privato 7/DSC_7924.webp", alt: "Casa E+R Torino - Vista 17", tall: true },
      { src: "/portfolio/privati/Villa Privato 7/DSC_7925.webp", alt: "Casa E+R Torino - Vista 18", tall: false },
      { src: "/portfolio/privati/Villa Privato 7/DSC_7926.webp", alt: "Casa E+R Torino - Vista 19", tall: false },
      { src: "/portfolio/privati/Villa Privato 7/DSC_7927.webp", alt: "Casa E+R Torino - Vista 20", tall: true },
      { src: "/portfolio/privati/Villa Privato 7/DSC_7928.webp", alt: "Casa E+R Torino - Vista 21", tall: false },
      { src: "/portfolio/privati/Villa Privato 7/DSC_7929.webp", alt: "Casa E+R Torino - Vista 22", tall: false },
      { src: "/portfolio/privati/Villa Privato 7/DSC_7941.webp", alt: "Casa E+R Torino - Vista 23", tall: true },
      { src: "/portfolio/privati/Villa Privato 7/DSC_7942.webp", alt: "Casa E+R Torino - Vista 24", tall: false },
      { src: "/portfolio/privati/Villa Privato 7/DSC_7943.webp", alt: "Casa E+R Torino - Vista 25", tall: false },
      { src: "/portfolio/privati/Villa Privato 7/DSC_7944.webp", alt: "Casa E+R Torino - Vista 26", tall: true },
      { src: "/portfolio/privati/Villa Privato 7/DSC_7945.webp", alt: "Casa E+R Torino - Vista 27", tall: false },
      { src: "/portfolio/privati/Villa Privato 7/DSC_7946.webp", alt: "Casa E+R Torino - Vista 28", tall: false },
      { src: "/portfolio/privati/Villa Privato 7/DSC_7949.webp", alt: "Casa E+R Torino - Vista 29", tall: true },
      { src: "/portfolio/privati/Villa Privato 7/DSC_7958.webp", alt: "Casa E+R Torino - Vista 30", tall: false },
      { src: "/portfolio/privati/Villa Privato 7/DSC_7960.webp", alt: "Casa E+R Torino - Vista 31", tall: false },
      { src: "/portfolio/privati/Villa Privato 7/DSC_7966.webp", alt: "Casa E+R Torino - Vista 32", tall: true },
      { src: "/portfolio/privati/Villa Privato 7/DSC_7975.webp", alt: "Casa E+R Torino - Vista 33", tall: false },
      { src: "/portfolio/privati/Villa Privato 7/DSC_7976.webp", alt: "Casa E+R Torino - Vista 34", tall: false },
      { src: "/portfolio/privati/Villa Privato 7/DSC_7977.webp", alt: "Casa E+R Torino - Vista 35", tall: true },
      { src: "/portfolio/privati/Villa Privato 7/DSC_8016.webp", alt: "Casa E+R Torino - Vista 36", tall: false },
      { src: "/portfolio/privati/Villa Privato 7/DSC_8017.webp", alt: "Casa E+R Torino - Vista 37", tall: false },
      { src: "/portfolio/privati/Villa Privato 7/DSC_8018.webp", alt: "Casa E+R Torino - Vista 38", tall: true },
      { src: "/portfolio/privati/Villa Privato 7/DSC_8019.webp", alt: "Casa E+R Torino - Vista 39", tall: false },
      { src: "/portfolio/privati/Villa Privato 7/DSC_8020.webp", alt: "Casa E+R Torino - Vista 40", tall: false },
      { src: "/portfolio/privati/Villa Privato 7/DSC_8021.webp", alt: "Casa E+R Torino - Vista 41", tall: true },
      { src: "/portfolio/privati/Villa Privato 7/DSC_8022.webp", alt: "Casa E+R Torino - Vista 42", tall: false },
      { src: "/portfolio/privati/Villa Privato 7/DSC_8023.webp", alt: "Casa E+R Torino - Vista 43", tall: false },
      { src: "/portfolio/privati/Villa Privato 7/DSC_8024.webp", alt: "Casa E+R Torino - Vista 44", tall: true },
      { src: "/portfolio/privati/Villa Privato 7/DSC_8059.webp", alt: "Casa E+R Torino - Vista 45", tall: false },
      { src: "/portfolio/privati/Villa Privato 7/DSC_8060.webp", alt: "Casa E+R Torino - Vista 46", tall: false },
      { src: "/portfolio/privati/Villa Privato 7/DSC_8061.webp", alt: "Casa E+R Torino - Vista 47", tall: true },
      { src: "/portfolio/privati/Villa Privato 7/DSC_8062.webp", alt: "Casa E+R Torino - Vista 48", tall: false },
      { src: "/portfolio/privati/Villa Privato 7/DSC_8063.webp", alt: "Casa E+R Torino - Vista 49", tall: false },
      { src: "/portfolio/privati/Villa Privato 7/DSC_8065.webp", alt: "Casa E+R Torino - Vista 50", tall: true },
    ],
  },

  // â”€â”€ 9 â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  {
    slug: "residenza-a-r-lombardia",
    title: "Residenza A+R",
    location: "Lombardia",
    category: "privati",
    description: "Villa privata con pavimentazioni e rivestimenti di qualità selezionati per valorizzare ogni ambiente.",
    coverImage: "/portfolio/privati/Villa Privato 8/DSC_8152.webp",
    tall: false,
    images: [
      { src: "/portfolio/privati/Villa Privato 8/DSC_8152.webp", alt: "Residenza A+R Lombardia - Vista 1", tall: false },
      { src: "/portfolio/privati/Villa Privato 8/DSC_8153.webp", alt: "Residenza A+R Lombardia - Vista 2", tall: true },
      { src: "/portfolio/privati/Villa Privato 8/DSC_8154.webp", alt: "Residenza A+R Lombardia - Vista 3", tall: false },
      { src: "/portfolio/privati/Villa Privato 8/DSC_8155.webp", alt: "Residenza A+R Lombardia - Vista 4", tall: false },
      { src: "/portfolio/privati/Villa Privato 8/DSC_8156.webp", alt: "Residenza A+R Lombardia - Vista 5", tall: true },
      { src: "/portfolio/privati/Villa Privato 8/DSC_8158.webp", alt: "Residenza A+R Lombardia - Vista 6", tall: false },
      { src: "/portfolio/privati/Villa Privato 8/DSC_8160.webp", alt: "Residenza A+R Lombardia - Vista 7", tall: false },
      { src: "/portfolio/privati/Villa Privato 8/DSC_8162.webp", alt: "Residenza A+R Lombardia - Vista 8", tall: true },
      { src: "/portfolio/privati/Villa Privato 8/DSC_8165.webp", alt: "Residenza A+R Lombardia - Vista 9", tall: false },
      { src: "/portfolio/privati/Villa Privato 8/DSC_8172.webp", alt: "Residenza A+R Lombardia - Vista 10", tall: false },
      { src: "/portfolio/privati/Villa Privato 8/DSC_8175.webp", alt: "Residenza A+R Lombardia - Vista 11", tall: true },
      { src: "/portfolio/privati/Villa Privato 8/DSC_8176.webp", alt: "Residenza A+R Lombardia - Vista 12", tall: false },
      { src: "/portfolio/privati/Villa Privato 8/DSC_8177.webp", alt: "Residenza A+R Lombardia - Vista 13", tall: false },
      { src: "/portfolio/privati/Villa Privato 8/DSC_8192.webp", alt: "Residenza A+R Lombardia - Vista 14", tall: true },
      { src: "/portfolio/privati/Villa Privato 8/DSC_8198.webp", alt: "Residenza A+R Lombardia - Vista 15", tall: false },
      { src: "/portfolio/privati/Villa Privato 8/DSC_8201.webp", alt: "Residenza A+R Lombardia - Vista 16", tall: false },
      { src: "/portfolio/privati/Villa Privato 8/DSC_8220.webp", alt: "Residenza A+R Lombardia - Vista 17", tall: true },
      { src: "/portfolio/privati/Villa Privato 8/DSC_8223.webp", alt: "Residenza A+R Lombardia - Vista 18", tall: false },
      { src: "/portfolio/privati/Villa Privato 8/DSC_8225.webp", alt: "Residenza A+R Lombardia - Vista 19", tall: false },
      { src: "/portfolio/privati/Villa Privato 8/DSC_8231.webp", alt: "Residenza A+R Lombardia - Vista 20", tall: true },
      { src: "/portfolio/privati/Villa Privato 8/DSC_8239.webp", alt: "Residenza A+R Lombardia - Vista 21", tall: false },
      { src: "/portfolio/privati/Villa Privato 8/DSC_8245.webp", alt: "Residenza A+R Lombardia - Vista 22", tall: false },
      { src: "/portfolio/privati/Villa Privato 8/DSC_8249.webp", alt: "Residenza A+R Lombardia - Vista 23", tall: true },
      { src: "/portfolio/privati/Villa Privato 8/DSC_8250.webp", alt: "Residenza A+R Lombardia - Vista 24", tall: false },
      { src: "/portfolio/privati/Villa Privato 8/DSC_8258.webp", alt: "Residenza A+R Lombardia - Vista 25", tall: false },
      { src: "/portfolio/privati/Villa Privato 8/DSC_8267.webp", alt: "Residenza A+R Lombardia - Vista 26", tall: true },
      { src: "/portfolio/privati/Villa Privato 8/DSC_8280.webp", alt: "Residenza A+R Lombardia - Vista 27", tall: false },
      { src: "/portfolio/privati/Villa Privato 8/DSC_8284.webp", alt: "Residenza A+R Lombardia - Vista 28", tall: false },
      { src: "/portfolio/privati/Villa Privato 8/DSC_8286.webp", alt: "Residenza A+R Lombardia - Vista 29", tall: true },
      { src: "/portfolio/privati/Villa Privato 8/DSC_8288.webp", alt: "Residenza A+R Lombardia - Vista 30", tall: false },
      { src: "/portfolio/privati/Villa Privato 8/DSC_8317.webp", alt: "Residenza A+R Lombardia - Vista 31", tall: false },
      { src: "/portfolio/privati/Villa Privato 8/DSC_8333.webp", alt: "Residenza A+R Lombardia - Vista 32", tall: true },
      { src: "/portfolio/privati/Villa Privato 8/DSC_8354.webp", alt: "Residenza A+R Lombardia - Vista 33", tall: false },
      { src: "/portfolio/privati/Villa Privato 8/DSC_8356.webp", alt: "Residenza A+R Lombardia - Vista 34", tall: false },
      { src: "/portfolio/privati/Villa Privato 8/DSC_8370.webp", alt: "Residenza A+R Lombardia - Vista 35", tall: true },
      { src: "/portfolio/privati/Villa Privato 8/DSC_8372.webp", alt: "Residenza A+R Lombardia - Vista 36", tall: false },
      { src: "/portfolio/privati/Villa Privato 8/DSC_8394.webp", alt: "Residenza A+R Lombardia - Vista 37", tall: false },
    ],
  },

  // â”€â”€ 10 â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  {
    slug: "scuola-elementare-santo-stefano-belbo",
    title: "Scuola Elementare",
    location: "Santo Stefano Belbo",
    category: "imprese",
    description: "Progetto commerciale con fornitura e posa di pavimenti e rivestimenti di pregio. Materiali selezionati per ambienti professionali con alto standard qualitativo.",
    coverImage: "/portfolio/imprese/Foto impresa 2 Santo stefano Belbo/IMG_5304.webp",
    tall: false,
    images: [
      { src: "/portfolio/imprese/Foto impresa 2 Santo stefano Belbo/IMG_5304.webp", alt: "Scuola Elementare Santo Stefano Belbo - Vista 1", tall: false },
      { src: "/portfolio/imprese/Foto impresa 2 Santo stefano Belbo/IMG_5305.webp", alt: "Scuola Elementare Santo Stefano Belbo - Vista 2", tall: true },
      { src: "/portfolio/imprese/Foto impresa 2 Santo stefano Belbo/IMG_5308.webp", alt: "Scuola Elementare Santo Stefano Belbo - Vista 3", tall: false },
      { src: "/portfolio/imprese/Foto impresa 2 Santo stefano Belbo/IMG_5309.webp", alt: "Scuola Elementare Santo Stefano Belbo - Vista 4", tall: false },
      { src: "/portfolio/imprese/Foto impresa 2 Santo stefano Belbo/IMG_5310.webp", alt: "Scuola Elementare Santo Stefano Belbo - Vista 5", tall: true },
      { src: "/portfolio/imprese/Foto impresa 2 Santo stefano Belbo/IMG_5313.webp", alt: "Scuola Elementare Santo Stefano Belbo - Vista 6", tall: false },
      { src: "/portfolio/imprese/Foto impresa 2 Santo stefano Belbo/IMG_5322.webp", alt: "Scuola Elementare Santo Stefano Belbo - Vista 7", tall: false },
      { src: "/portfolio/imprese/Foto impresa 2 Santo stefano Belbo/IMG_5323.webp", alt: "Scuola Elementare Santo Stefano Belbo - Vista 8", tall: true },
      { src: "/portfolio/imprese/Foto impresa 2 Santo stefano Belbo/IMG_5325.webp", alt: "Scuola Elementare Santo Stefano Belbo - Vista 9", tall: false },
      { src: "/portfolio/imprese/Foto impresa 2 Santo stefano Belbo/IMG_5330.webp", alt: "Scuola Elementare Santo Stefano Belbo - Vista 10", tall: false },
      { src: "/portfolio/imprese/Foto impresa 2 Santo stefano Belbo/IMG_5333.webp", alt: "Scuola Elementare Santo Stefano Belbo - Vista 11", tall: true },
      { src: "/portfolio/imprese/Foto impresa 2 Santo stefano Belbo/IMG_5336.webp", alt: "Scuola Elementare Santo Stefano Belbo - Vista 12", tall: false },
      { src: "/portfolio/imprese/Foto impresa 2 Santo stefano Belbo/IMG_5338.webp", alt: "Scuola Elementare Santo Stefano Belbo - Vista 13", tall: false },
      { src: "/portfolio/imprese/Foto impresa 2 Santo stefano Belbo/IMG_5342.webp", alt: "Scuola Elementare Santo Stefano Belbo - Vista 14", tall: true },
      { src: "/portfolio/imprese/Foto impresa 2 Santo stefano Belbo/IMG_5344.webp", alt: "Scuola Elementare Santo Stefano Belbo - Vista 15", tall: false },
      { src: "/portfolio/imprese/Foto impresa 2 Santo stefano Belbo/IMG_5345.webp", alt: "Scuola Elementare Santo Stefano Belbo - Vista 16", tall: false },
      { src: "/portfolio/imprese/Foto impresa 2 Santo stefano Belbo/IMG_5346.webp", alt: "Scuola Elementare Santo Stefano Belbo - Vista 17", tall: true },
      { src: "/portfolio/imprese/Foto impresa 2 Santo stefano Belbo/IMG_5350.webp", alt: "Scuola Elementare Santo Stefano Belbo - Vista 18", tall: false },
      { src: "/portfolio/imprese/Foto impresa 2 Santo stefano Belbo/IMG_5351.webp", alt: "Scuola Elementare Santo Stefano Belbo - Vista 19", tall: false },
      { src: "/portfolio/imprese/Foto impresa 2 Santo stefano Belbo/IMG_5353.webp", alt: "Scuola Elementare Santo Stefano Belbo - Vista 20", tall: true },
      { src: "/portfolio/imprese/Foto impresa 2 Santo stefano Belbo/IMG_5356.webp", alt: "Scuola Elementare Santo Stefano Belbo - Vista 21", tall: false },
      { src: "/portfolio/imprese/Foto impresa 2 Santo stefano Belbo/IMG_5358.webp", alt: "Scuola Elementare Santo Stefano Belbo - Vista 22", tall: false },
      { src: "/portfolio/imprese/Foto impresa 2 Santo stefano Belbo/IMG_5360.webp", alt: "Scuola Elementare Santo Stefano Belbo - Vista 23", tall: true },
      { src: "/portfolio/imprese/Foto impresa 2 Santo stefano Belbo/IMG_5362.webp", alt: "Scuola Elementare Santo Stefano Belbo - Vista 24", tall: false },
      { src: "/portfolio/imprese/Foto impresa 2 Santo stefano Belbo/IMG_5365.webp", alt: "Scuola Elementare Santo Stefano Belbo - Vista 25", tall: false },
      { src: "/portfolio/imprese/Foto impresa 2 Santo stefano Belbo/IMG_5366.webp", alt: "Scuola Elementare Santo Stefano Belbo - Vista 26", tall: true },
      { src: "/portfolio/imprese/Foto impresa 2 Santo stefano Belbo/IMG_5369.webp", alt: "Scuola Elementare Santo Stefano Belbo - Vista 27", tall: false },
    ],
  },
  {
    slug: "residenza-ristrutturata-savigliano",
    title: "Residenza Ristrutturata",
    location: "Savigliano",
    category: "privati",
    description:
      "Ristrutturazione completa di una residenza privata a Savigliano. Nuovi pavimenti e rivestimenti in ogni ambiente, dalla zona giorno ai bagni, per un risultato moderno ed elegante che valorizza ogni spazio.",
    coverImage:
      "/portfolio/privati/Ristrutturazione Savigliano Privato 2/IMG_9604.webp",
    tall: false,
    coverPosition: "object-right",
    images: [
      { src: "/portfolio/privati/Ristrutturazione Savigliano Privato 2/IMG_9604.webp", alt: "Residenza Ristrutturata Savigliano - Copertina", tall: false },
      { src: "/portfolio/privati/Ristrutturazione Savigliano Privato 2/IMG_9563.webp", alt: "Residenza Ristrutturata Savigliano - Vista 1", tall: true },
      { src: "/portfolio/privati/Ristrutturazione Savigliano Privato 2/IMG_9565.webp", alt: "Residenza Ristrutturata Savigliano - Vista 2", tall: false },
      { src: "/portfolio/privati/Ristrutturazione Savigliano Privato 2/IMG_9569.webp", alt: "Residenza Ristrutturata Savigliano - Vista 3", tall: false },
      { src: "/portfolio/privati/Ristrutturazione Savigliano Privato 2/IMG_9570.webp", alt: "Residenza Ristrutturata Savigliano - Vista 4", tall: true },
      { src: "/portfolio/privati/Ristrutturazione Savigliano Privato 2/IMG_9574.webp", alt: "Residenza Ristrutturata Savigliano - Vista 5", tall: false },
      { src: "/portfolio/privati/Ristrutturazione Savigliano Privato 2/IMG_9575.webp", alt: "Residenza Ristrutturata Savigliano - Vista 6", tall: false },
      { src: "/portfolio/privati/Ristrutturazione Savigliano Privato 2/IMG_9577.webp", alt: "Residenza Ristrutturata Savigliano - Vista 7", tall: true },
      { src: "/portfolio/privati/Ristrutturazione Savigliano Privato 2/IMG_9578.webp", alt: "Residenza Ristrutturata Savigliano - Vista 8", tall: false },
      { src: "/portfolio/privati/Ristrutturazione Savigliano Privato 2/IMG_9579.webp", alt: "Residenza Ristrutturata Savigliano - Vista 9", tall: false },
      { src: "/portfolio/privati/Ristrutturazione Savigliano Privato 2/IMG_9584.webp", alt: "Residenza Ristrutturata Savigliano - Vista 10", tall: true },
      { src: "/portfolio/privati/Ristrutturazione Savigliano Privato 2/IMG_9585.webp", alt: "Residenza Ristrutturata Savigliano - Vista 11", tall: false },
      { src: "/portfolio/privati/Ristrutturazione Savigliano Privato 2/IMG_9586.webp", alt: "Residenza Ristrutturata Savigliano - Vista 12", tall: false },
      { src: "/portfolio/privati/Ristrutturazione Savigliano Privato 2/IMG_9590.webp", alt: "Residenza Ristrutturata Savigliano - Vista 13", tall: true },
      { src: "/portfolio/privati/Ristrutturazione Savigliano Privato 2/IMG_9600.webp", alt: "Residenza Ristrutturata Savigliano - Vista 14", tall: false },
      { src: "/portfolio/privati/Ristrutturazione Savigliano Privato 2/IMG_9605.webp", alt: "Residenza Ristrutturata Savigliano - Vista 15", tall: false },
      { src: "/portfolio/privati/Ristrutturazione Savigliano Privato 2/IMG_9608.webp", alt: "Residenza Ristrutturata Savigliano - Vista 16", tall: true },
      { src: "/portfolio/privati/Ristrutturazione Savigliano Privato 2/IMG_9611.webp", alt: "Residenza Ristrutturata Savigliano - Vista 17", tall: false },
      { src: "/portfolio/privati/Ristrutturazione Savigliano Privato 2/IMG_9612.webp", alt: "Residenza Ristrutturata Savigliano - Vista 18", tall: false },
      { src: "/portfolio/privati/Ristrutturazione Savigliano Privato 2/IMG_9617.webp", alt: "Residenza Ristrutturata Savigliano - Vista 19", tall: true },
      { src: "/portfolio/privati/Ristrutturazione Savigliano Privato 2/IMG_9619.webp", alt: "Residenza Ristrutturata Savigliano - Vista 20", tall: false },
    ],
  },
];

export function getProjectBySlug(slug: string): Project | undefined {
  return projects.find((p) => p.slug === slug);
}
